function Populate-Windows {
	Param(
		[Parameter(Mandatory=$true,Position=0)] [String]$ProgramName
	)
	winget install -e --id $ProgramName --force
}
$pop_apps = "Microsoft.AppInstaller",
"7zip.7zip",
"Gyan.FFmpeg",
"yt-dlp.yt-dlp",
"Google.PlayGames.Beta",
"Mozilla.Firefox",
"PostgreSQL.PostgreSQL.16",
"PostgreSQL.pgAdmin",
"NVIDIA.CUDA",
"OpenJS.NodeJS",
"SonicPi.SonicPi",
"MichaelTippach.ASIO4ALL",
"AnyDeskSoftwareGmbH.AnyDesk",
"Kitware.CMake",
"Microsoft.VisualStudio.2022.BuildTools",
"EpicGames.EpicGamesLauncher", 
"Spotify.Spotify",
"Ytmdesktop.Ytmdesktop",
"Obsidian.Obsidian",
"File-New-Project.EarTrumpet",
"Telegram.TelegramDesktop",
"Bandisoft.Honeyview",
"VideoLAN.VLC",
"Valve.Steam",
"GOG.Galaxy",
"Brave.Brave",
"Baidu.TeraBox",
"PeterPawlowski.foobar2000",
"Nvidia.GeForceExperience",
"Nvidia.CUDA",
"Nvidia.GeForceNow",
"BleachBit.BleachBit",
"RiotGames.LeagueOfLegends.EUW",
"Notepad++.Notepad++",
"AntibodySoftware.WizTree",
"AppWork.JDownloader",
"Discord.Discord",
"Adobe.Acrobat.Reader.64-bit",
"TheDocumentFoundation.LibreOffice",
"Autodesk.DesktopApp",
"Python.Python.3.11",
"TortoiseGit.TortoiseGit",
"GitHub.GitLFS",
"Git.Git",
"OBSProject.OBSStudio",
"Oracle.VirtualBox",
"Transmission.Transmission",
"calibre.calibre",
"Mozilla.Thunderbird",
"Google.Drive",
"TeamViewer.TeamViewer",
"BlenderFoundation.Blender",
"Microsoft.WindowsTerminal",
"Mega.MEGASync",
"Unity.UnityHub",
"AnyDeskSoftwareGmbH.AnyDesk",
"JetBrains.PyCharm.Community",
"GeoGebra.GraphingCalculator",
"AivarAnnamaa.Thonny",
"TenacityTeam.Tenacity",
"Fork.Fork",
"Postman.Postman",
"Microsoft.DotNet.SDK.7",
"Microsoft.PowerToys",
"VSCodium.VSCodium.Insiders",
"VB-Audio.Voicemeeter.Banana",
"OpenVPNTechnologies.OpenVPNConnect"

foreach ($pop_app in $pop_apps)
{
	Write-Host $pop_app
	Populate-Windows $pop_app
}
