function Debloat-Windows {
	Param(
		[Parameter(Mandatory=$true,Position=0)] [String]$ProgramName
	)
	Get-AppxPackage -name $ProgramName | Remove-AppxPackage
}
$bloat_apps = "Microsoft.ZuneMusic", 
"Microsoft.Music.Preview", 
"Microsoft.XboxGameCallableUI", 
"Microsoft.XboxIdentityProvider", 
"Microsoft.BingTravel", 
"Microsoft.BingHealthAndFitness", 
"Microsoft.BingFoodAndDrink", 
"Microsoft.People", 
"Microsoft.BingFinance", 
"Microsoft.3DBuilder", 
"Microsoft.WindowsCalculator", 
"Microsoft.BingNews", 
"Microsoft.XboxApp", 
"Microsoft.BingSports", 
"Microsoft.WindowsCamera", 
"Microsoft.Getstarted", 
"Microsoft.Office.OneNote", 
"Microsoft.WindowsMaps", 
"Microsoft.MicrosoftSolitaireCollection", 
"Microsoft.MicrosoftOffi1ceHub", 
"Microsoft.BingWeather", 
"Microsoft.BioEnrollment", 
"Microsoft.WindowsStore", 
"Microsoft.Windows.Photos", 
"Microsoft.WindowsPhone",
"Microsoft.GetHelp",
"Microsoft.Messaging",
"Microsoft.Microsoft3DViewer",
"Microsoft.MicrosoftOfficeHub",
"Microsoft.NetworkSpeedTest",
"Microsoft.News",
"Microsoft.Office.Lens",
"Microsoft.Office.Sway",
"Microsoft.OneConnect",
"Microsoft.Print3D",
"Microsoft.RemoteDesktop",
"Microsoft.SkypeApp",
"Microsoft.StorePurchaseApp",
"Microsoft.Office.Todo.List",
"Microsoft.Whiteboard",
"Microsoft.WindowsAlarms",
"microsoft.windowscommunicationsapps",
"Microsoft.WindowsFeedbackHub",
"Microsoft.WindowsSoundRecorder",
"Microsoft.Xbox.TCUI",
"Microsoft.XboxGameOverlay",
"Microsoft.XboxSpeechToTextOverlay",
"Microsoft.ZuneVideo",
"*EclipseManager*",
"*ActiproSoftwareLLC*",
"*AdobeSystemsIncorporated.AdobePhotoshopExpress*",
"*Duolingo-LearnLanguagesforFree*",
"*PandoraMediaInc*",
"*CandyCrush*",
"*BubbleWitch3Saga*",
"*Wunderlist*",
"*Flipboard*",
"*Twitter*",
"*Facebook*",
"*Spotify*",
"*Minecraft*",
"*Royal Revolt*",
"*Sway*",
"*Speed Test*",
"*Dolby*"

foreach ($bloat_app in $bloat_apps)
{
	Write-Host $bloat_app
	Debloat-Windows $bloat_app
}
